* Uberphoenix

Like many people I am a fan of the Hoster [[https://uberspace.de][Uberspace]]. If you don't know them and you are looking for a flexible hoster to try out new things, consider joining them. They have a first rate support and a price range starting at 5€. This low price comes with... well, a price: It's a shared hoster, hence you will have to do some things a bit different. :)

I'm also a fan of Elixir and the PhoenixFramework. This repositories shows you one way how to setup a Phoenix Application within uberspace.

** Preparing your Uberspace
*** Setup Postgres

Basically what I did was following the instructions from the [[https://lab.uberspace.de/guide_postgresql/][Postgresql Manual Page]].

These were my exact steps, after sshing to my uberspace:
#+BEGIN_SRC bash
  uberspace tools version use postgresql 13
  openssl rand -hex 32 > ~/pgpass.temp
  echo "*:*:*:$(whoami):$(cat ~/pgpass.temp)" > ~/.pgpass # you can and probably SHOULD edit the 3 stars at the beginning - google for pgpass file for more information
  chmod 0600 ~/.pgpass  
  initdb --pwfile ~/pgpass.temp --auth=scram-sha-256 -E UTF8 -D ~/opt/postgresql/data/
  rm ~/pgpass.temp
  echo 'export PGPASSFILE=$HOME/.pgpass' >> ~/.bash_profile
  echo 'export PGHOST=localhost' >> ~/.bash_profile
  echo 'export PGPORT=5432' >> ~/.bash_profile
  source ~./bash_profile
  cp ~/opt/postgresql/data/postgresql.conf ~/opt/postgresql/data/postgresql.conf_bak # safety backup in case the following sed is broken :)
  sed -i "s/^unix_socket_directories =.*/unix_socket_directories = '\/home\/$(whoami)\/tmp'/g" # sed to change unix_socket_directories
  # Create an ini file
  touch ~/etc/services.d/postgresql.ini
  echo "[program:postgresql]"                                  >> ~/etc/services.d/postgresql.ini
  echo "command=postgres -D %(ENV_HOME)s/opt/postgresql/data/" >> ~/etc/services.d/postgresql.ini
  echo "autostart=yes"                                         >> ~/etc/services.d/postgresql.ini
  echo "autorestart=yes"                                       >> ~/etc/services.d/postgresql.ini
  echo "startsec=15"                                           >> ~/etc/services.d/postgresql.ini
  supervisorctl reread
  supervisorctl update
#+END_SRC

After that you should have a running postgres database. Be aware that the user will me your uberspace user, not the default ~postgres~

*** Setup OTP and Elixir

Updating your Elixir is done by updating the OTP version for your account by running:


#+BEGIN_SRC bash
  uberspace tools version use erlang 24
#+END_SRC

There is currently no way to use elixir in a specific version on Uberspace. But you could probably build it from source if you really want to.

*** Setup the Environment
Before we go into the core of the application, we will setup some environment variables within our uberspace. Let's create a local env file

#+BEGIN_SRC bash
  touch ~/.uberphoenix_env
  echo 'PHX_HOST=example.com'              >> ~/.uberphoenix_env # enter your domain
  echo 'PHX_PORT=1337'                     >> ~/.uberphoenix_env # enter a port you want your backend to run, 1337 is just an example here
  echo 'PHX_SECRET_KEY_BASE=YOURSECRETKEY' >> ~/.uberphoenix_env # some secret key, can be be generated by `mix phx.gen.secret`
  echo 'PHX_PATH=/YOUR/PATH'               >> ~/.uberphoenix_env # if you want to setup a specific path for your application, default should be "/"
  echo 'MIX_ENV=prod'                      >> ~/.uberphoenix_env 
  echo 'source $HOME/.uberphoenix_env'     >> ~/.bash_profile
  source ~/.bash_profile
#+END_SRC

*** Setup a Backend

On a shared hoster it's hard to deploy your Application on the default ports for http or https. Luckily Uberspace offers a way around by its [[https://manual.uberspace.de/web-backends/][Web Backend Tooling]].
It offers you a way to setup your Application with any port and forward web traffic to that port.

If the phoenix application is the only thing that shoudl take http requests within your account you can just run the following snippet and be done.

#+BEGIN_SRC bash
  uberspace web backend set / --http --port "$PHX_PORT"
#+END_SRC

Now you have a backend that listens to https and http calls and refers these to your phoenix application.

**** Running Phoenix And Other Applications

Many Uberspace users will have multiple tools within their account and they don't want the Phoenix Application to be the only thing reachable from outside.
Luckily Uberspace has you covered by one of two methods: you can either provide a specific subdomain for your Application or you specify a path for your Application.

***** Solution 1: Setup a Subdomain

If you have a specific Subdomain, just put it into your ~.uberphoenix_env~ as the ~PHX_HOST~ and run the following snippet:

#+BEGIN_SRC bash
  uberspace web backend set "$PHX_HOST" --http --port "$PHX_PORT"
#+END_SRC

***** DOING Solution 2: Setup Phoenix for a specific path

You can setup a path by giving the uberspace tool your specific ~PHX_PATH~

#+BEGIN_SRC bash
  uberspace web backend set "$PHX_PATH" --http --port "$PHX_PORT"
#+END_SRC

If you are using Phoenix LiveView, you should as well add the path ~/live~ as well.

#+BEGIN_SRC bash
  uberspace web backend set /live --http --port "$PHX_PORT"
#+END_SRC

You can also look for the route ~/live~ within your application (probably in ~lib/uberphoenix/endpoint.ex~ and ~assets/js/app.js~). 

*** Test Run for Your Phoenix Application






